import{chainLabel}from"@/lib/chains";
import{maybeApi}from"@/lib/api";import{Unavailable}from"@/components/DataState";import{usd}from"@/lib/format";
export const metadata={title:"Dependencies"};
type E={source_type:string;source_id:string;relationship:string;target_type:string;target_id:string;exposure_usd:number|null;weight:number|null;observed_at:string};type R={root:{type:string;id:string};edges:E[]};
type Market={id:string;marketName:string;assetSymbol:string|null;protocolName:string|null;chainName:string|null;liquidityUsd:number|null};
type EntityRow={id:string;label:string;markets:number;liquidityUsd:number|null};type EntityData={kind:"asset"|"protocol"|"chain";rows:EntityRow[]};
const kinds=["market","asset","protocol","chain"] as const;type Kind=typeof kinds[number];
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const s=await searchParams,rawType=one(s.type)??"market",type=(kinds as readonly string[]).includes(rawType)?rawType as Kind:"market",id=one(s.id)??"";
 const markets=await maybeApi<Market[]>("/analytics/markets?limit=250"),entities=type!=="market"?await maybeApi<EntityData>(`/analytics/entities/${type}`):null;
 const options=type==="market"?(markets?.data??[]).map(m=>({id:m.id,label:[m.assetSymbol??m.marketName,m.protocolName,m.chainName].filter(Boolean).join(" · "),liquidity:m.liquidityUsd})):(entities?.data.rows??[]).map(x=>({id:x.id,label:x.label,liquidity:x.liquidityUsd}));
 options.sort((a,b)=>(b.liquidity??0)-(a.liquidity??0));const selected=options.find(x=>x.id===id),r=id?await maybeApi<R>(`/dependencies/${type}/${encodeURIComponent(id)}/graph?depth=2`):null;
 return <div className="page"><div className="page-head"><div><h1 className="page-title">Dependency Map</h1><div className="page-sub">Choose a market or entity by name. Tokos keeps provider identifiers internal.</div></div></div><form className="filter-bar"><select className="select" name="type" defaultValue={type}>{kinds.map(x=><option key={x} value={x}>{x[0]?.toUpperCase()+x.slice(1)}</option>)}</select><select className="select" name="id" defaultValue={id}><option value="">Choose {type}</option>{options.map(x=><option key={x.id} value={x.id}>{x.label}{x.liquidity!=null?` · ${usd(x.liquidity)} liquidity`:""}</option>)}</select><button className="btn">Map</button></form>
 {!id?<Unavailable title="Choose an entity" detail="Select a market, asset, protocol, or network to inspect its observed dependencies."/>:!r?<Unavailable title="Dependency graph unavailable" detail="No live observed dependency graph is available for this selection."/>:<><div className="page-meta section">{selected?.label??"Selected entity"}</div><div className="table-wrap"><table className="data"><thead><tr><th>Relationship</th><th>Dependency</th><th>Type</th><th className="num">Exposure</th><th className="num">Weight</th><th>Observed</th></tr></thead><tbody>{r.data.edges.map((e,i)=><tr key={i}><td>{friendly(e.relationship)}</td><td className="identity">{labelForEdge(e,markets?.data??[])}</td><td>{e.target_type}</td><td className="num">{usd(e.exposure_usd)}</td><td className="num">{e.weight==null?"—":(e.weight*100).toFixed(1)+"%"}</td><td>{new Date(e.observed_at).toISOString().slice(0,16).replace("T"," ")+" UTC"}</td></tr>)}</tbody></table></div></>}</div>}
function one(v:string|string[]|undefined){return Array.isArray(v)?v[0]:v}function friendly(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}function labelForEdge(e:E,markets:Market[]){if(e.target_type==="market"){const m=markets.find(x=>x.id===e.target_id);if(m)return [m.assetSymbol??m.marketName,m.protocolName,m.chainName].filter(Boolean).join(" · ")}if(e.target_type==="chain")return chainLabel(e.target_id);return e.target_id}
