import{chainLabel}from"@/lib/chains";
import{maybeApi}from"@/lib/api";import{Unavailable}from"@/components/DataState";import{date,usd}from"@/lib/format";
export const metadata={title:"Dependencies"};
type E={source_type:string;source_id:string;relationship:string;target_type:string;target_id:string;target_label?:string|null;detail?:string|null;depth?:number|null;source?:string|null;exposure_usd:number|null;weight:number|null;observed_at:string};
type UnderlyingStep={symbol:string;role:string;relation:string|null;source:string};type R={root:{type:string;id:string};market?:{name:string;asset:string;protocol:string;network:string;maturity:string|null;tvlUsd:number|null;liquidityUsd:number|null};underlyingPath?:UnderlyingStep[];edges:E[]};
type Market={id:string;marketName:string;assetSymbol:string|null;protocolName:string|null;chainName:string|null;chainId?:string|null;liquidityUsd:number|null;maturity?:string|null};
type EntityRow={id:string;label:string;markets:number;liquidityUsd:number|null};type EntityData={kind:"asset"|"protocol"|"chain";rows:EntityRow[]};
const kinds=["market","asset","protocol","chain"] as const;type Kind=typeof kinds[number];
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const s=await searchParams,rawType=one(s.type)??"market",type=(kinds as readonly string[]).includes(rawType)?rawType as Kind:"market",id=one(s.id)??"";
 const markets=await maybeApi<Market[]>("/analytics/markets?limit=250"),entities=type!=="market"?await maybeApi<EntityData>(`/analytics/entities/${type}`):null;
 const options=type==="market"?(markets?.data??[]).map(m=>({id:m.id,label:m.marketName,sub:m.maturity?date(m.maturity):null,liquidity:m.liquidityUsd})):(entities?.data.rows??[]).map(x=>({id:x.id,label:x.label,sub:null,liquidity:x.liquidityUsd}));
 options.sort((a,b)=>(b.liquidity??0)-(a.liquidity??0));const selected=options.find(x=>x.id===id),r=id?await maybeApi<R>(`/dependencies/${type}/${encodeURIComponent(id)}/graph?depth=2`):null;
 const structural=r?.data.edges.filter(e=>!["source_protocol","network","uses_asset","operated_by","deployed_on"].includes(e.relationship))??[],context=r?.data.edges.filter(e=>["source_protocol","network","uses_asset","operated_by","deployed_on"].includes(e.relationship))??[];
 return <div className="page"><div className="page-head"><div><h1 className="page-title">Dependency Map</h1><div className="page-sub">Inspect what a market is structurally dependent on. Provider identifiers remain internal.</div></div></div>
 <form className="filter-bar"><select className="select" name="type" defaultValue={type}>{kinds.map(x=><option key={x} value={x}>{x[0]?.toUpperCase()+x.slice(1)}</option>)}</select><select className="select" name="id" defaultValue={id}><option value="">Choose {type}</option>{options.map(x=><option key={x.id} value={x.id}>{x.label}{x.sub?` · ${x.sub}`:""}</option>)}</select><button className="btn">Inspect</button></form>
 {!id?<Unavailable title="Choose an entity" detail="Select a market, asset, protocol, or network to inspect its live dependency structure."/>:!r?<Unavailable title="Dependency graph unavailable" detail="No live observed dependency graph is available for this selection."/>:<>
 {r.data.market&&<div className="metrics section"><M l="Market" v={r.data.market.name}/><M l="Protocol" v={r.data.market.protocol}/><M l="Network" v={r.data.market.network}/><M l="Maturity" v={r.data.market.maturity?date(r.data.market.maturity):"—"}/><M l="TVL" v={usd(r.data.market.tvlUsd)}/><M l="Liquidity" v={usd(r.data.market.liquidityUsd)}/></div>}
 {r.data.underlyingPath&&r.data.underlyingPath.length>1&&<section className="section"><div className="section-bar"><div><h2 className="section-title">Underlying path</h2><div className="page-sub">Recursive economic exposure, resolved up to three layers from source-backed relationships.</div></div></div><div className="underlying-path">{r.data.underlyingPath.map((x,i)=><div className="underlying-step" key={`${x.symbol}:${i}`}><div className="underlying-depth">Layer {i+1}</div><strong>{x.symbol}</strong><span>{x.role}</span>{i<r.data.underlyingPath!.length-1&&<b className="underlying-arrow">→</b>}</div>)}</div></section>}
 <section className="section"><div className="section-bar"><div><h2 className="section-title">Instrument structure</h2><div className="page-sub">Live PT, YT, SY/wrapper, and underlying relationships from the provider plus verified recursive backing layers.</div></div></div>
 {!structural.length?<Unavailable title="No deeper instrument dependencies exposed" detail="The provider does not expose a deeper token structure for this selection. Tokos will not invent one."/>:<div className="table-wrap"><table className="data"><thead><tr><th>Layer</th><th>Relationship</th><th>Dependency</th><th>Role</th><th>Evidence</th></tr></thead><tbody>{structural.map((e,i)=><tr key={i}><td className="mono">{e.depth??1}</td><td>{friendly(e.relationship)}</td><td className="identity" style={{paddingLeft:`${Math.max(0,(e.depth??1)-1)*14}px`}}>{labelForEdge(e,markets?.data??[])}</td><td>{e.target_type}</td><td>{e.source??e.detail??"Live provider metadata"}</td></tr>)}</tbody></table></div>}</section>
 {context.length>0&&<section className="section"><div className="section-bar"><div><h2 className="section-title">Market context</h2><div className="page-sub">Supporting protocol and network context, separated from structural dependencies.</div></div></div><div className="table-wrap"><table className="data"><thead><tr><th>Relationship</th><th>Context</th><th>Type</th><th>Observed</th></tr></thead><tbody>{context.map((e,i)=><tr key={i}><td>{friendly(e.relationship)}</td><td className="identity">{labelForEdge(e,markets?.data??[])}</td><td>{e.target_type}</td><td>{new Date(e.observed_at).toISOString().slice(0,16).replace("T"," ")+" UTC"}</td></tr>)}</tbody></table></div></section>}
 </>}</div>}
function one(v:string|string[]|undefined){return Array.isArray(v)?v[0]:v}
function friendly(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function labelForEdge(e:E,markets:Market[]){if(e.target_label)return e.target_label;if(e.target_type==="market"){const m=markets.find(x=>x.id===e.target_id);if(m)return m.marketName}if(e.target_type==="chain"||e.target_type==="network")return chainLabel(e.target_id);return e.target_id}
function M({l,v}:{l:string;v:string}){return <div className="metric"><div className="metric-label">{l}</div><div className="metric-value">{v}</div></div>}
