import{maybeApi,qs}from"@/lib/api";import{TimeChart}from"@/components/Chart";import{ScatterCompareChart}from"@/components/IntelligenceVisuals";import{Unavailable}from"@/components/DataState";import{bps,date,pct,usd}from"@/lib/format";import{chainLabel}from"@/lib/chains";
export const metadata={title:"Compare"};
type MarketOption={id:string;marketName:string;assetSymbol:string|null;protocolName:string|null;chainId:string;chainName:string|null;liquidityUsd:number|null;fixedApy:number|null;impliedApy:number|null;supplyApr:number|null;maturity:string|null};
type Row={id:string;marketName:string;assetSymbol:string|null;protocolName:string|null;chainId?:string|null;chainName:string|null;supplyApr:number|null;fixedApy:number|null;impliedApy:number|null;liquidityUsd:number|null;tvlUsd:number|null;depositsUsd:number|null;debtUsd:number|null;utilization:number|null;maturity:string|null;change24hBps:number|null;effectiveRate:number|null;priceImpactBps:number|null;depthNotionalUsd:number|null};
type Point={marketId:string;observedAt:string;rate:number|null;liquidityUsd:number|null;tvlUsd:number|null;utilization:number|null};type Compare={markets:Row[];history:Point[];methodologyVersion:string};
type RatingRow={id:string;rating:{rating:string;score:number|null;coverage:number;worstSeverity?:string|null}};
const metricOptions=[["rate","Yield"],["liquidity","Liquidity"],["tvl","TVL"],["volatility","30D volatility"],["tenor","Tenor"]]as const;
export default async function ComparePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const s=await searchParams,[marketRes,riskRes]=await Promise.all([maybeApi<MarketOption[]>("/analytics/markets?limit=250"),maybeApi<RatingRow[]>("/risk/markets?limit=250")]),options=[...(marketRes?.data??[])].sort((a,b)=>(b.liquidityUsd??0)-(a.liquidityUsd??0));
 const legacy=(Array.isArray(s.markets)?s.markets.join(","):s.markets??"").split(",").filter(Boolean),picked=[one(s.m1),one(s.m2),one(s.m3),one(s.m4)].filter((x):x is string=>Boolean(x));
 const ids=[...new Set(picked.length?picked:legacy.length?legacy:options.slice(0,3).map(x=>x.id))].slice(0,4),days=finite(one(s.days),90),x=one(s.x)??"rate",y=one(s.y)??"liquidity",bubble=one(s.bubble)??"tvl";
 const res=ids.length>=2?await maybeApi<Compare>(`/analytics/compare?${qs({marketIds:ids.join(","),days})}`):null,ratingMap=new Map((riskRes?.data??[]).map(r=>[r.id,r.rating]));
 return <div className="page"><div className="page-head"><div><h1 className="page-title">Compare Markets</h1><div className="page-sub">Compare live yield markets side by side across return, evidence rating, liquidity, TVL, maturity, and historical behavior.</div></div><div className="page-meta">2 to 4 markets</div></div>
 <form className="compare-controls"><div className="compare-market-grid">{[0,1,2,3].map(i=><label key={i}><span>Market {i+1}</span><select className="select" name={`m${i+1}`} defaultValue={ids[i]??""}><option value="">{i<2?"Choose market":"Optional"}</option>{options.map(m=><option key={m.id} value={m.id}>{marketLabel(m)}</option>)}</select></label>)}</div><div className="compare-options"><label><span>History window</span><select className="select" name="days" defaultValue={String(days)}><option value="30">30 days</option><option value="90">90 days</option><option value="365">1 year</option></select></label><button className="btn primary">Compare</button></div></form>
 {ids.length<2?<Unavailable title="Choose at least two markets" detail="Select markets above. Tokos keeps provider IDs internal."/>:!res?<Unavailable title="Comparison unavailable" detail="Live comparison data could not be loaded for the selected markets."/>:<CompareView data={res.data} ratings={ratingMap} markets={ids.join(",")} days={days} x={x} y={y} bubble={bubble}/>}</div>
}
function CompareView({data:d,ratings,markets,days,x,y,bubble}:{data:Compare;ratings:Map<string,RatingRow["rating"]>;markets:string;days:number;x:string;y:string;bubble:string}){
 const grouped=new Map<string,Point[]>();for(const p of d.history){const a=grouped.get(p.marketId)??[];a.push(p);grouped.set(p.marketId,a)}const stats=new Map(d.markets.map(m=>[m.id,derive(m,grouped.get(m.id)??[])]));
 const rates=d.markets.map(m=>stats.get(m.id)?.rate).filter((v):v is number=>v!=null),yieldSpread=rates.length>1?Math.max(...rates)-Math.min(...rates):null,totalLiquidity=d.markets.reduce((a,m)=>a+(m.liquidityUsd??0),0),rated=d.markets.filter(m=>ratings.get(m.id)?.rating!=="NR"&&ratings.get(m.id)?.rating).length;
 const rateSeries=d.markets.map(m=>({name:m.assetSymbol??m.marketName,data:(grouped.get(m.id)??[]).map(p=>[p.observedAt,p.rate]as[string,number|null])})),tvlSeries=d.markets.map(m=>({name:m.assetSymbol??m.marketName,data:(grouped.get(m.id)??[]).map(p=>[p.observedAt,p.tvlUsd]as[string,number|null])}));
 const scatter=d.markets.flatMap(m=>{const st=stats.get(m.id)!;const xv=valueFor(x,m,st),yv=valueFor(y,m,st),bv=valueFor(bubble,m,st);return xv==null||yv==null||bv==null?[]:[{label:m.assetSymbol??m.marketName,x:xv,y:yv,bubble:bv}]});
 return <><div className="compare-summary section"><K l="Markets" v={String(d.markets.length)}/><K l="Yield spread" v={yieldSpread==null?"—":bps(yieldSpread*10000)}/><K l="Combined liquidity" v={usd(totalLiquidity)}/><K l="Evidence rated" v={`${rated}/${d.markets.length}`}/></div>
 <div className="table-wrap section"><table className="data compare-table"><thead><tr><th>Market</th><th>Rating</th><th className="num">Yield</th><th className="num">30D change</th><th className="num">30D volatility</th><th className="num">Liquidity</th><th className="num">TVL</th><th>Maturity</th><th>Network</th></tr></thead><tbody>{d.markets.map(m=>{const st=stats.get(m.id)!,r=ratings.get(m.id);return <tr key={m.id}><td><div className="identity">{m.assetSymbol??m.marketName}</div><div className="credit-market-name">{m.protocolName??"—"}</div></td><td>{r?<span className="rating">{r.rating}</span>:"—"}{r&&<div className="credit-market-name">{r.score==null?"No score":`${r.score.toFixed(1)} · ${r.coverage}% coverage`}</div>}</td><td className="num identity">{pct(st.rate)}</td><td className="num">{bps(st.change30d)}</td><td className="num">{pct(st.volatility)}</td><td className="num">{usd(m.liquidityUsd)}</td><td className="num">{usd(m.tvlUsd)}</td><td>{m.maturity?date(m.maturity):"—"}{st.tenor!=null&&<div className="credit-market-name">{Math.round(st.tenor)} days</div>}</td><td>{chainLabel(m.chainId,m.chainName)}</td></tr>})}</tbody></table></div>
 <section className="section analytics-grid two"><Panel title="Yield history" note={`${days} day live history`}><TimeChart series={rateSeries}/></Panel><Panel title="TVL history" note={`${days} day live history`}><TimeChart series={tvlSeries} yFormat="usd"/></Panel></section>
 <section className="panel section"><div className="panel-head"><span className="panel-title">Relative positioning</span><form className="compare-axis-form"><input type="hidden" name="markets" value={markets}/><input type="hidden" name="days" value={days}/><label>X<select name="x" defaultValue={x}>{metricOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Y<select name="y" defaultValue={y}>{metricOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Bubble<select name="bubble" defaultValue={bubble}>{metricOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button className="btn">Update</button></form></div><div className="panel-body">{scatter.length>=2?<ScatterCompareChart points={scatter} xLabel={labelFor(x)} yLabel={labelFor(y)} bubbleLabel={labelFor(bubble)}/>:<Unavailable title="Relative positioning unavailable" detail="The selected dimensions need at least two markets with live observations."/ >}</div></section></>
}
function derive(m:Row,rows:Point[]){const sorted=[...rows].sort((a,b)=>Date.parse(a.observedAt)-Date.parse(b.observedAt)),vals=sorted.map(p=>p.rate).filter((v):v is number=>v!=null),rate=m.fixedApy??m.impliedApy??m.supplyApr,latest=sorted.at(-1)?.observedAt,change=(d:number)=>{if(rate==null||!latest)return null;const target=Date.parse(latest)-d*86400000,point=sorted.filter(p=>p.rate!=null).sort((a,b)=>Math.abs(Date.parse(a.observedAt)-target)-Math.abs(Date.parse(b.observedAt)-target))[0];return point?.rate==null?null:(rate-point.rate)*10000},mean=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,volatility=vals.length>=5&&mean!=null?Math.sqrt(vals.reduce((a,b)=>a+(b-mean)**2,0)/(vals.length-1)):null,tenor=m.maturity&&latest?Math.max(0,(Date.parse(m.maturity)-Date.parse(latest))/86400000):null;return{rate,change30d:change(30),volatility,tenor}}
function valueFor(k:string,m:Row,s:ReturnType<typeof derive>){return k==="rate"?s.rate:k==="liquidity"?m.liquidityUsd:k==="tvl"?m.tvlUsd:k==="volatility"?s.volatility:k==="tenor"?s.tenor:null}
function marketLabel(m:MarketOption){return [m.assetSymbol??m.marketName,m.protocolName,chainLabel(m.chainId,m.chainName),pct(m.fixedApy??m.impliedApy??m.supplyApr)].filter(Boolean).join(" · ")}
function labelFor(k:string){return metricOptions.find(([v])=>v===k)?.[1]??k}function one(v:string|string[]|undefined){return Array.isArray(v)?v[0]:v}function finite(v:string|undefined,fallback:number){const n=Number(v);return Number.isFinite(n)?n:fallback}function Panel({title,note,children}:{title:string;note?:string;children:React.ReactNode}){return <div className="panel"><div className="panel-head"><span className="panel-title">{title}</span>{note&&<span className="panel-note">{note}</span>}</div><div className="panel-body">{children}</div></div>}function K({l,v}:{l:string;v:string}){return <div><span>{l}</span><strong>{v}</strong></div>}
