import{basisBps,METHODOLOGY_VERSION}from"@tokos-data/analytics";import type{ServerEnv}from"@tokos-data/config";import{rateHorizonGrid,rateNotionalGrid}from"@tokos-data/config";import{services}from"./ingest.js";
type FixedRow={id:string;asset_id:string;asset_group:string;maturity:string;rate:number;liquidity_usd:number|null};
type FloatingRow={id:string;asset_group:string;rate:number;liquidity_usd:number|null};
export async function ingestCrossProviderBasis(env:ServerEnv){
 const{repo}=services(env),horizons=rateHorizonGrid(env),notionals=rateNotionalGrid(env);let pairs=0;
 const fixedResult=await repo.pool.query(`SELECT id,asset_id,asset_group,maturity,COALESCE(fixed_apy,implied_apy) rate,liquidity_usd FROM mv_latest_markets WHERE provider='pendle' AND status='active' AND NOT stale AND asset_group IS NOT NULL AND maturity>now() AND COALESCE(fixed_apy,implied_apy) IS NOT NULL ORDER BY liquidity_usd DESC NULLS LAST`),fixed=fixedResult.rows as FixedRow[];
 for(const notionalUsd of notionals){
  const floatingResult=await repo.pool.query(`SELECT lm.id,lm.asset_group,COALESCE(ed.effective_apr,ed.apr_at_amount,lm.supply_apr) rate,lm.liquidity_usd FROM mv_latest_markets lm LEFT JOIN LATERAL(SELECT effective_apr,apr_at_amount FROM execution_depth_snapshots e WHERE e.market_id=lm.id AND e.notional_usd=$1 AND e.side='supply' AND e.observed_at>=now()-interval '2 hours' ORDER BY e.observed_at DESC LIMIT 1)ed ON TRUE WHERE lm.provider='1delta' AND lm.status='active' AND NOT lm.stale AND lm.asset_group IS NOT NULL AND COALESCE(ed.effective_apr,ed.apr_at_amount,lm.supply_apr) IS NOT NULL ORDER BY lm.asset_group,COALESCE(ed.effective_apr,ed.apr_at_amount,lm.supply_apr) DESC,lm.liquidity_usd DESC NULLS LAST`,[notionalUsd]),floatingRows=floatingResult.rows as FloatingRow[],bestFloating=new Map<string,FloatingRow>();
  for(const row of floatingRows)if(!bestFloating.has(row.asset_group))bestFloating.set(row.asset_group,row);
  for(const horizonDays of horizons){const now=Date.now(),tolerance=Math.max(14,horizonDays*.35),byGroup=new Map<string,FixedRow[]>();for(const row of fixed){const tenor=(new Date(row.maturity).getTime()-now)/86400000;if(!Number.isFinite(tenor)||Math.abs(tenor-horizonDays)>tolerance)continue;const list=byGroup.get(row.asset_group)??[];list.push(row);byGroup.set(row.asset_group,list)}
   for(const[group,rows]of byGroup){const floating=bestFloating.get(group);if(!floating)continue;rows.sort((a,b)=>{const da=Math.abs((new Date(a.maturity).getTime()-now)/86400000-horizonDays),db=Math.abs((new Date(b.maturity).getTime()-now)/86400000-horizonDays);return da-db||(Number(b.liquidity_usd??0)-Number(a.liquidity_usd??0))});for(const fixedRow of rows.slice(0,3)){const fixedRate=Number(fixedRow.rate),floatingRate=Number(floating.rate),spread=basisBps(fixedRate,floatingRate);if(!Number.isFinite(fixedRate)||!Number.isFinite(floatingRate)||spread==null)continue;await repo.upsertBasis({assetId:fixedRow.asset_id,observedAt:new Date().toISOString(),horizonDays,notionalUsd,fixedMarketId:fixedRow.id,floatingMarketId:floating.id,fixedRate,floatingRate,basisBps:spread,methodologyVersion:METHODOLOGY_VERSION});pairs++;}}
  }
 }
 return{pairs,notionals:notionals.length,horizons:horizons.length};
}
