type Envelope<T>={data:T;meta:{asOf:string;stale:boolean;requestId:string;nextCursor?:string|null;hasMore?:boolean}};

type TokenObject={address?:string;symbol?:string;name?:string;decimals?:number;price?:{usd?:number|null}};
type Token=TokenObject|string;
type PendleDetails={liquidity?:number|null;totalTvl?:number|null;tradingVolume?:number|null;underlyingApy?:number|null;impliedApy?:number|null};
type PendleMarket={chainId:string|number;address:string;expiry:string|number;impliedApy?:number|null;underlyingApy?:number|null;tvl?:{usd?:number|null};liquidity?:{usd?:number|null};volume24h?:{usd?:number|null};details?:PendleDetails;pt?:Token;yt?:Token;sy?:Token;underlyingAsset?:Token;name?:string;protocol?:string};
type Page={total?:number;totalCount?:number;markets?:PendleMarket[];results?:PendleMarket[];data?:{total?:number;totalCount?:number;markets?:PendleMarket[];results?:PendleMarket[]}};
type HistoricalPoint={timestamp:string;maxApy?:number|null;baseApy?:number|null;underlyingApy?:number|null;impliedApy?:number|null;tvl?:number|null};
type HistoricalPage={results?:HistoricalPoint[]};
type MarketHistory={market:PendleMarket;points:HistoricalPoint[]};

const PENDLE=(process.env.PENDLE_API_BASE_URL??"https://api-v2.pendle.finance/core").replace(/\/$/,"");
const chainNames:Record<string,string>={"1":"Ethereum","10":"Optimism","56":"BNB Chain","100":"Gnosis","130":"Unichain","146":"Sonic","42161":"Arbitrum","8453":"Base","5000":"Mantle","80094":"Berachain"};
const slug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const assetGroup=(s:string)=>{const x=s.toUpperCase();if(["USDC","USDBC"].includes(x))return"usdc";if(["USDT","USD₮0"].includes(x))return"usdt";if(["ETH","WETH"].includes(x))return"eth";if(["BTC","WBTC","CBBTC","TBTC"].includes(x))return"btc";if(["USDE","SUSDE"].includes(x))return"usde";return slug(x)};
const toMs=(x:string|number)=>typeof x==="number"?(x>1e12?x:x*1000):(/^\d+(?:\.\d+)?$/.test(x)?Number(x)*(Number(x)>1e12?1:1000):Date.parse(x));
const num=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)?x:null;
const tokenSymbol=(t:Token|undefined)=>typeof t==="object"&&t!==null?t.symbol:undefined;
const impliedApyOf=(m:PendleMarket)=>num(m.impliedApy)??num(m.details?.impliedApy);
const underlyingApyOf=(m:PendleMarket)=>num(m.underlyingApy)??num(m.details?.underlyingApy);
const tvlOf=(m:PendleMarket)=>num(m.tvl?.usd)??num(m.details?.totalTvl);
const liquidityOf=(m:PendleMarket)=>num(m.liquidity?.usd)??num(m.details?.liquidity);

function pageRows(j:Page){return j.markets??j.results??j.data?.markets??j.data?.results??[]}
function pageTotal(j:Page){return j.total??j.totalCount??j.data?.total??j.data?.totalCount}
async function fetchPage(skip:number,limit:number){const r=await fetch(`${PENDLE}/v2/markets/all?limit=${limit}&skip=${skip}`,{headers:{accept:"application/json"},next:{revalidate:60}});if(!r.ok)throw new Error(`Pendle ${r.status}`);return await r.json() as Page}
async function markets(){const limit=100,first=await fetchPage(0,limit),firstRows=pageRows(first),total=pageTotal(first)??firstRows.length;const offsets=[];for(let skip=limit;skip<total;skip+=limit)offsets.push(skip);const rest=offsets.length?await Promise.all(offsets.map(skip=>fetchPage(skip,limit))):[];const all=[...firstRows,...rest.flatMap(pageRows)],now=Date.now();return all.filter(m=>m?.address&&Number.isFinite(toMs(m.expiry))&&toMs(m.expiry)>now)}
function symbolOf(m:PendleMarket){return tokenSymbol(m.underlyingAsset)??tokenSymbol(m.sy)??tokenSymbol(m.pt)?.replace(/^PT-/,"")??m.name?.replace(/^PT[- ]/i,"")??"UNKNOWN"}
function nameOf(m:PendleMarket){return m.name??tokenSymbol(m.pt)??`Pendle ${symbolOf(m)}`}
function protocolNameOf(m:PendleMarket){return m.protocol?.trim()||"Pendle"}
function protocolIdOf(m:PendleMarket){return slug(protocolNameOf(m))||"pendle"}
function idOf(m:PendleMarket){return `pendle:${m.chainId}:${m.address.toLowerCase()}`}
function maturityOf(m:PendleMarket){return new Date(toMs(m.expiry)).toISOString()}
function chainName(id:string){return chainNames[id]??`Chain ${id}`}
function median(v:number[]){if(!v.length)return null;const s=[...v].sort((a,b)=>a-b),i=Math.floor(s.length/2);return s.length%2?s[i]??null:((s[i-1]??0)+(s[i]??0))/2}
function std(v:number[]){if(v.length<2)return null;const mean=v.reduce((a,b)=>a+b,0)/v.length;return Math.sqrt(v.reduce((a,b)=>a+(b-mean)**2,0)/(v.length-1))}
function historyRef(p:HistoricalPoint){const underlying=num(p.underlyingApy);return underlying!=null&&underlying!==0?underlying:num(p.baseApy)}
function queryDays(path:string){try{const raw=Number(new URL(path,"https://tokos.local").searchParams.get("days")??30);return[7,30,90,365].includes(raw)?raw:30}catch{return 30}}

async function fetchHistory(m:PendleMarket,days:number):Promise<HistoricalPoint[]>{try{const end=new Date(),start=new Date(end.getTime()-Math.max(days,8)*86400000);const url=`${PENDLE}/v3/${m.chainId}/markets/${m.address}/historical-data?time_frame=day&timestamp_start=${encodeURIComponent(start.toISOString())}&timestamp_end=${encodeURIComponent(end.toISOString())}`;const r=await fetch(url,{headers:{accept:"application/json"},next:{revalidate:300}});if(!r.ok)return[];const j=await r.json() as HistoricalPage;return(j.results??[]).filter(p=>p.timestamp&&num(p.impliedApy)!=null).sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp))}catch{return[]}}
async function sampleHistory(rows:PendleMarket[],days:number){const sample=[...rows].filter(m=>impliedApyOf(m)!=null).sort((a,b)=>(liquidityOf(b)??0)-(liquidityOf(a)??0)).slice(0,8);return Promise.all(sample.map(async market=>({market,points:await fetchHistory(market,days)})))}
function pointAtOrBefore(points:HistoricalPoint[],target:number){let best:HistoricalPoint|undefined;for(const p of points){const t=Date.parse(p.timestamp);if(Number.isFinite(t)&&t<=target&&(!best||t>Date.parse(best.timestamp)))best=p}return best}
function changeBps(current:number|null,prior:HistoricalPoint|undefined){const old=prior?num(prior.impliedApy):null;return current!=null&&old!=null?(current-old)*10000:null}
function aggregateHistory(series:MarketHistory[]){const byDay=new Map<string,Array<{fixed:number;floating:number|null;tvl:number|null}>>();for(const {points} of series)for(const p of points){const fixed=num(p.impliedApy);if(fixed==null)continue;const day=new Date(p.timestamp).toISOString().slice(0,10),list=byDay.get(day)??[];list.push({fixed,floating:historyRef(p),tvl:num(p.tvl)});byDay.set(day,list)}return[...byDay.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([day,list])=>{const fixed=list.map(x=>x.fixed),floating=list.map(x=>x.floating).filter((x):x is number=>x!=null),weighted=list.filter(x=>(x.tvl??0)>0),den=weighted.reduce((a,x)=>a+(x.tvl??0),0),weightedYield=den?weighted.reduce((a,x)=>a+x.fixed*(x.tvl??0),0)/den:null;return{observedAt:`${day}T00:00:00.000Z`,medianYield:median(fixed),weightedYield,fixedYield:weightedYield??median(fixed),floatingYield:median(floating),borrowRate:null,tvlUsd:list.reduce((a,x)=>a+(x.tvl??0),0)||null,liquidityUsd:null,utilization:null}})}
function moverRows(series:MarketHistory[],asOf:string){const now=Date.parse(asOf);return series.map(({market,points})=>{const current=impliedApyOf(market),d1=changeBps(current,pointAtOrBefore(points,now-86400000)),d7=changeBps(current,pointAtOrBefore(points,now-7*86400000));return{id:idOf(market),assetSymbol:symbolOf(market),assetId:slug(symbolOf(market)),marketName:nameOf(market),protocolName:protocolNameOf(market),change24hBps:d1,change7dBps:d7,liquidityUsd:liquidityOf(market)}}).filter(x=>x.change24hBps!=null||x.change7dBps!=null).sort((a,b)=>Math.max(Math.abs(b.change24hBps??0),Math.abs(b.change7dBps??0))-Math.max(Math.abs(a.change24hBps??0),Math.abs(a.change7dBps??0))).slice(0,8)}

function overview(rows:PendleMarket[],asOf:string,series:MarketHistory[]){const rates=rows.map(impliedApyOf).filter((x):x is number=>x!==null),tvl=rows.reduce((a,m)=>a+(tvlOf(m)??0),0),liq=rows.reduce((a,m)=>a+(liquidityOf(m)??0),0),weightedDen=rows.reduce((a,m)=>a+(tvlOf(m)??0),0),weightedNum=rows.reduce((a,m)=>a+(tvlOf(m)??0)*(impliedApyOf(m)??0),0),assets=new Map<string,{symbol:string;value:number;markets:number}>(),chains=new Map<string,{name:string;value:number;markets:number}>(),protocols=new Map<string,{id:string;name:string;value:number;markets:number}>();for(const m of rows){const s=symbolOf(m),a=assets.get(s)??{symbol:s,value:0,markets:0};a.value+=tvlOf(m)??0;a.markets++;assets.set(s,a);const c=String(m.chainId),q=chains.get(c)??{name:chainName(c),value:0,markets:0};q.value+=tvlOf(m)??0;q.markets++;chains.set(c,q);const pid=protocolIdOf(m),p=protocols.get(pid)??{id:pid,name:protocolNameOf(m),value:0,markets:0};p.value+=tvlOf(m)??0;p.markets++;protocols.set(pid,p)}return{summary:{trackedTvl:tvl||null,totalDebt:null,liquidity:liq||null,medianYield:median(rates),weightedYield:weightedDen?weightedNum/weightedDen:null,bestYield:rates.length?Math.max(...rates):null,activeMarkets:rows.length,assets:assets.size,protocols:protocols.size,chains:chains.size},history:aggregateHistory(series),structure:{protocols:[...protocols.values()].map(x=>({protocol_id:x.id,protocol_name:x.name,value:x.value,markets:x.markets})),chains:[...chains.entries()].map(([id,x])=>({chain_id:id,chain_name:x.name,value:x.value,markets:x.markets})),assets:[...assets.values()].map(x=>({asset_group:assetGroup(x.symbol),asset_symbol:x.symbol,value:x.value,markets:x.markets}))},heatmap:rows.map(m=>({asset:symbolOf(m),protocol_id:protocolIdOf(m),protocol:protocolNameOf(m),rate:impliedApyOf(m),liquidity_usd:liquidityOf(m),tvl_usd:tvlOf(m),as_of:asOf})),landscape:rows.map(m=>({id:idOf(m),market_name:nameOf(m),protocol_id:protocolIdOf(m),protocol_name:protocolNameOf(m),chain_id:String(m.chainId),chain_name:chainName(String(m.chainId)),asset_symbol:symbolOf(m),asset_group:assetGroup(symbolOf(m)),maturity:maturityOf(m),rate:impliedApyOf(m),liquidity_usd:liquidityOf(m),tvl_usd:tvlOf(m),rate_type:"fixed",observed_at:asOf})),movers:moverRows(series,asOf)}}

function screener(rows:PendleMarket[],asOf:string,series:MarketHistory[]){const histories=new Map(series.map(x=>[idOf(x.market),x.points])),now=Date.parse(asOf);return rows.map(m=>{const maturity=maturityOf(m),days=Math.max(0,(new Date(maturity).getTime()-Date.now())/86400000),s=symbolOf(m),points=histories.get(idOf(m))??[],current=impliedApyOf(m),rates=points.map(p=>num(p.impliedApy)).filter((x):x is number=>x!=null),diffs=rates.slice(1).map((x,i)=>(x-(rates[i]??x))*10000),rank=current==null||!rates.length?null:rates.filter(x=>x<=current).length/rates.length;return{id:idOf(m),assetId:slug(s),assetSymbol:s,assetGroup:assetGroup(s),marketName:nameOf(m),protocolId:protocolIdOf(m),protocolName:protocolNameOf(m),chainId:String(m.chainId),chainName:chainName(String(m.chainId)),rateType:"fixed",supplyApr:null,borrowApr:null,fixedApy:current,impliedApy:current,underlyingApy:underlyingApyOf(m),rewardApr:null,liquidityUsd:liquidityOf(m),tvlUsd:tvlOf(m),depositsUsd:null,debtUsd:null,utilization:null,change24hBps:changeBps(current,pointAtOrBefore(points,now-86400000)),change7dBps:changeBps(current,pointAtOrBefore(points,now-7*86400000)),change30dBps:changeBps(current,pointAtOrBefore(points,now-30*86400000)),change1hBps:null,liquidityChange24h:null,tvlChange24h:null,utilizationChange24h:null,rateChangeVolatility30d:std(diffs),headlineEffectiveGapBps:null,volatility30d:std(rates),ratePercentile:rank,daysToMaturity:days,maturity,observedAt:asOf,stale:false,rateTrend:points.map(p=>[p.timestamp,num(p.impliedApy)])}})}

export async function liveFallback<T>(path:string):Promise<Envelope<T>|null>{if(typeof window!=="undefined")return null;if(!path.startsWith("/analytics/overview")&&!path.startsWith("/analytics/markets")&&!path.startsWith("/market-trends")&&!path.startsWith("/analytics/market-changes"))return null;try{const rows=await markets(),asOf=new Date().toISOString(),days=queryDays(path),series=await sampleHistory(rows,path.startsWith("/analytics/overview")?days:30),meta={asOf,stale:false,requestId:"pendle-live-fallback"};if(path.startsWith("/analytics/overview"))return{data:overview(rows,asOf,series) as T,meta};if(path.startsWith("/analytics/markets"))return{data:screener(rows,asOf,series) as T,meta};return{data:{} as T,meta}}catch{return null}}
