type Envelope<T>={data:T;meta:{asOf:string;stale:boolean;requestId:string;nextCursor?:string|null;hasMore?:boolean}};

type TokenObject={address?:string;symbol?:string;name?:string;decimals?:number;price?:{usd?:number|null}};
type Token=TokenObject|string;
type PendleDetails={liquidity?:number|null;totalTvl?:number|null;tradingVolume?:number|null;underlyingApy?:number|null;impliedApy?:number|null};
type PendleMarket={chainId:string|number;address:string;expiry:string|number;impliedApy?:number|null;underlyingApy?:number|null;tvl?:{usd?:number|null};liquidity?:{usd?:number|null};volume24h?:{usd?:number|null};details?:PendleDetails;pt?:Token;yt?:Token;sy?:Token;underlyingAsset?:Token;name?:string;protocol?:string};
type Page={total?:number;totalCount?:number;markets?:PendleMarket[];results?:PendleMarket[];data?:{total?:number;totalCount?:number;markets?:PendleMarket[];results?:PendleMarket[]}};

const PENDLE=(process.env.PENDLE_API_BASE_URL??"https://api-v2.pendle.finance/core").replace(/\/$/,"");
const chainNames:Record<string,string>={"1":"Ethereum","10":"Optimism","56":"BNB Chain","146":"Sonic","42161":"Arbitrum","8453":"Base","5000":"Mantle","80094":"Berachain"};
const slug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const assetGroup=(s:string)=>{const x=s.toUpperCase();if(["USDC","USDBC"].includes(x))return"usdc";if(["USDT","USD₮0"].includes(x))return"usdt";if(["ETH","WETH"].includes(x))return"eth";if(["BTC","WBTC","CBBTC","TBTC"].includes(x))return"btc";if(["USDE","SUSDE"].includes(x))return"usde";return slug(x)};
const toMs=(x:string|number)=>typeof x==="number"?(x>1e12?x:x*1000):(/^\d+(?:\.\d+)?$/.test(x)?Number(x)*(Number(x)>1e12?1:1000):Date.parse(x));
const num=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)?x:null;
const tokenSymbol=(t:Token|undefined)=>typeof t==="object"&&t!==null?t.symbol:undefined;
const impliedApyOf=(m:PendleMarket)=>num(m.impliedApy)??num(m.details?.impliedApy);
const underlyingApyOf=(m:PendleMarket)=>num(m.underlyingApy)??num(m.details?.underlyingApy);
const tvlOf=(m:PendleMarket)=>num(m.tvl?.usd)??num(m.details?.totalTvl);
const liquidityOf=(m:PendleMarket)=>num(m.liquidity?.usd)??num(m.details?.liquidity);

function pageRows(j:Page){return j.markets??j.results??j.data?.markets??j.data?.results??[]}
function pageTotal(j:Page){return j.total??j.totalCount??j.data?.total??j.data?.totalCount}
async function fetchPage(skip:number,limit:number){const r=await fetch(`${PENDLE}/v2/markets/all?limit=${limit}&skip=${skip}`,{headers:{accept:"application/json"},next:{revalidate:60}});if(!r.ok)throw new Error(`Pendle ${r.status}`);return await r.json() as Page}
async function markets(){const limit=100,first=await fetchPage(0,limit),firstRows=pageRows(first),total=pageTotal(first)??firstRows.length;const offsets=[];for(let skip=limit;skip<total;skip+=limit)offsets.push(skip);const rest=offsets.length?await Promise.all(offsets.map(skip=>fetchPage(skip,limit))):[];const all=[...firstRows,...rest.flatMap(pageRows)],now=Date.now();return all.filter(m=>m?.address&&Number.isFinite(toMs(m.expiry))&&toMs(m.expiry)>now)}
function symbolOf(m:PendleMarket){return tokenSymbol(m.underlyingAsset)??tokenSymbol(m.sy)??tokenSymbol(m.pt)?.replace(/^PT-/,"")??m.name?.replace(/^PT[- ]/i,"")??"UNKNOWN"}
function nameOf(m:PendleMarket){return m.name??tokenSymbol(m.pt)??`Pendle ${symbolOf(m)}`}
function idOf(m:PendleMarket){return `pendle:${m.chainId}:${m.address.toLowerCase()}`}
function maturityOf(m:PendleMarket){return new Date(toMs(m.expiry)).toISOString()}
function chainName(id:string){return chainNames[id]??`Chain ${id}`}
function median(v:number[]){if(!v.length)return null;const s=[...v].sort((a,b)=>a-b),i=Math.floor(s.length/2);return s.length%2?s[i]??null:((s[i-1]??0)+(s[i]??0))/2}

function overview(rows:PendleMarket[],asOf:string){const rates=rows.map(impliedApyOf).filter((x):x is number=>x!==null),tvl=rows.reduce((a,m)=>a+(tvlOf(m)??0),0),liq=rows.reduce((a,m)=>a+(liquidityOf(m)??0),0),weightedDen=rows.reduce((a,m)=>a+(tvlOf(m)??0),0),weightedNum=rows.reduce((a,m)=>a+(tvlOf(m)??0)*(impliedApyOf(m)??0),0),assets=new Map<string,{symbol:string;value:number;markets:number}>(),chains=new Map<string,{name:string;value:number;markets:number}>();for(const m of rows){const s=symbolOf(m),a=assets.get(s)??{symbol:s,value:0,markets:0};a.value+=tvlOf(m)??0;a.markets++;assets.set(s,a);const c=String(m.chainId),q=chains.get(c)??{name:chainName(c),value:0,markets:0};q.value+=tvlOf(m)??0;q.markets++;chains.set(c,q)}return{summary:{trackedTvl:tvl||null,totalDebt:null,liquidity:liq||null,medianYield:median(rates),weightedYield:weightedDen?weightedNum/weightedDen:null,bestYield:rates.length?Math.max(...rates):null,activeMarkets:rows.length,assets:assets.size,protocols:1,chains:chains.size},history:[],structure:{protocols:[{protocol_id:"pendle",protocol_name:"Pendle",value:tvl,markets:rows.length}],chains:[...chains.entries()].map(([id,x])=>({chain_id:id,chain_name:x.name,value:x.value,markets:x.markets})),assets:[...assets.values()].map(x=>({asset_group:assetGroup(x.symbol),asset_symbol:x.symbol,value:x.value,markets:x.markets}))},heatmap:rows.map(m=>({asset:symbolOf(m),protocol_id:"pendle",protocol:"Pendle",rate:impliedApyOf(m),liquidity_usd:liquidityOf(m),tvl_usd:tvlOf(m),as_of:asOf})),landscape:rows.map(m=>({id:idOf(m),market_name:nameOf(m),protocol_id:"pendle",protocol_name:"Pendle",chain_id:String(m.chainId),chain_name:chainName(String(m.chainId)),asset_symbol:symbolOf(m),asset_group:assetGroup(symbolOf(m)),maturity:maturityOf(m),rate:impliedApyOf(m),liquidity_usd:liquidityOf(m),tvl_usd:tvlOf(m),rate_type:"fixed",observed_at:asOf})),movers:[]}}

function screener(rows:PendleMarket[],asOf:string){return rows.map(m=>{const maturity=maturityOf(m),days=Math.max(0,(new Date(maturity).getTime()-Date.now())/86400000),s=symbolOf(m);return{id:idOf(m),assetId:slug(s),assetSymbol:s,assetGroup:assetGroup(s),marketName:nameOf(m),protocolId:"pendle",protocolName:"Pendle",chainId:String(m.chainId),chainName:chainName(String(m.chainId)),rateType:"fixed",supplyApr:null,borrowApr:null,fixedApy:impliedApyOf(m),impliedApy:impliedApyOf(m),underlyingApy:underlyingApyOf(m),rewardApr:null,liquidityUsd:liquidityOf(m),tvlUsd:tvlOf(m),depositsUsd:null,debtUsd:null,utilization:null,change24hBps:null,change7dBps:null,change30dBps:null,change1hBps:null,liquidityChange24h:null,tvlChange24h:null,utilizationChange24h:null,rateChangeVolatility30d:null,headlineEffectiveGapBps:null,volatility30d:null,ratePercentile:null,daysToMaturity:days,maturity,observedAt:asOf,stale:false,rateTrend:[]}})}

export async function liveFallback<T>(path:string):Promise<Envelope<T>|null>{if(typeof window!=="undefined")return null;if(!path.startsWith("/analytics/overview")&&!path.startsWith("/analytics/markets")&&!path.startsWith("/market-trends")&&!path.startsWith("/analytics/market-changes"))return null;try{const rows=await markets(),asOf=new Date().toISOString(),meta={asOf,stale:false,requestId:"pendle-live-fallback"};if(path.startsWith("/analytics/overview"))return{data:overview(rows,asOf) as T,meta};if(path.startsWith("/analytics/markets"))return{data:screener(rows,asOf) as T,meta};return{data:{} as T,meta}}catch{return null}}
