import Link from "next/link";
import {maybeApi} from "@/lib/api";
import {Unavailable} from "@/components/DataState";
import {pct,usd} from "@/lib/format";

type Kind="asset"|"protocol"|"chain";
type Row={id:string;label:string;name:string;markets:number;assets?:number;protocols?:number;chains?:number;medianRate:number|null;bestRate:number|null;depositsUsd:number|null;debtUsd:number|null;liquidityUsd:number|null;utilization:number|null};
type Data={kind:Kind;rows:Row[]};
export async function EntityDirectoryPage({kind,title}:{kind:Kind;title:string}){const res=await maybeApi<Data>(`/analytics/entities/${kind}`);if(!res)return <div className="page"><Unavailable title={`${title} unavailable`}/></div>;const base=kind==="asset"?"asset":kind;return <div className="page"><div className="page-head"><h1 className="page-title">{title}</h1><div className="page-meta">{res.data.rows.length.toLocaleString()} tracked</div></div><div className="table-wrap"><table className="data"><thead><tr><th>{kind==="asset"?"Asset":kind==="protocol"?"Protocol":"Chain"}</th><th className="num">Markets</th>{kind!=="asset"&&<th className="num">Assets</th>}{kind!=="protocol"&&<th className="num">Protocols</th>}{kind!=="chain"&&<th className="num">Chains</th>}<th className="num">Median Yield</th><th className="num">Best Yield</th><th className="num">Deposits / TVL</th><th className="num">Liquidity</th>{kind!=="asset"&&<th className="num">Utilization</th>}</tr></thead><tbody>{res.data.rows.map(r=><tr key={r.id}><td className="identity"><Link href={`/${base}/${encodeURIComponent(r.id)}`}>{r.label}</Link></td><td className="num">{r.markets.toLocaleString()}</td>{kind!=="asset"&&<td className="num">{(r.assets??0).toLocaleString()}</td>}{kind!=="protocol"&&<td className="num">{(r.protocols??0).toLocaleString()}</td>}{kind!=="chain"&&<td className="num">{(r.chains??0).toLocaleString()}</td>}<td className="num">{pct(r.medianRate)}</td><td className="num">{pct(r.bestRate)}</td><td className="num">{usd(r.depositsUsd)}</td><td className="num">{usd(r.liquidityUsd)}</td>{kind!=="asset"&&<td className="num">{pct(r.utilization,1)}</td>}</tr>)}</tbody></table></div></div>}
