import {maybeApi} from "@/lib/api";
import {Metric} from "@/components/Metric";
import {MarketsTable,type MarketRow} from "@/components/MarketsTable";
import {TimeChart,CurveChart} from "@/components/Chart";
import {BubbleChart,DistributionChart,HorizontalBarChart} from "@/components/ChartsAdvanced";
import {FlowDiagram,RelationshipGraph,TreemapChart} from "@/components/IntelligenceVisuals";
import {StaleNotice,Unavailable} from "@/components/DataState";
import {pct,usd} from "@/lib/format";

type Kind="asset"|"protocol"|"chain";
type History={observedAt:string;rate:number|null;fixedRate:number|null;floatingRate:number|null;borrowRate:number|null;tvlUsd:number|null;liquidityUsd:number|null;utilization:number|null};
type Breakdown={key:string;label:string;value:number|null;markets:number};
type Landscape={id:string;market_name:string;protocol_id:string;protocol_name:string|null;chain_id:string;chain_name:string|null;asset_id:string;asset_symbol:string|null;maturity:string|null;rate:number|null;liquidity_usd:number|null;tvl_usd:number|null;rate_type:string;observed_at:string};
type EntityData={kind:Kind;entity:{id:string;label:string;name:string;asset_group?:string;slug?:string};summary:{marketCount:number;protocolCount:number;chainCount:number;assetCount:number;depositsUsd:number|null;debtUsd:number|null;liquidityUsd:number|null;medianRate:number|null;bestRate:number|null;utilization:number|null;fixedMarkets:number;floatingMarkets:number};history:History[];breakdowns:{protocols:Breakdown[];chains:Breakdown[];assets:Breakdown[]};distribution:number[];landscape:Landscape[];markets:MarketRow[];methodologyVersion:string};

export async function EntityAnalyticsPage({kind,id}:{kind:Kind;id:string}){const res=await maybeApi<EntityData>(`/analytics/entities/${kind}/${encodeURIComponent(id)}`);if(!res)return <div className="page"><Unavailable title="Entity analytics unavailable"/></div>;const d=res.data,s=d.summary,label=d.entity.label??d.entity.name??d.entity.id,asOf=Date.parse(res.meta.asOf||"")||Date.now(),bubbles=d.landscape.filter(x=>x.maturity&&x.rate!=null).map(x=>({x:Math.max(0,(new Date(x.maturity!).getTime()-asOf)/86400000),y:x.rate!,size:x.liquidity_usd??0,label:x.market_name,group:x.protocol_name??x.protocol_id,detail:x.asset_symbol??x.asset_id})).filter(x=>x.x>0),curve=d.landscape.filter(x=>x.maturity&&x.rate!=null).map(x=>({tenorDays:Math.max(0,(new Date(x.maturity!).getTime()-asOf)/86400000),fixed:x.rate_type==="fixed"||x.rate_type==="hybrid"?x.rate:null,floating:x.rate_type==="floating"||x.rate_type==="hybrid"?x.rate:null})).sort((a,b)=>a.tenorDays-b.tenorDays),breakdown=kind==="asset"?d.breakdowns.protocols:kind==="protocol"?d.breakdowns.assets:d.breakdowns.protocols,secondary=kind==="asset"?d.breakdowns.chains:kind==="protocol"?d.breakdowns.chains:d.breakdowns.assets;return <div className="page"><div className="page-head"><h1 className="page-title">{label}</h1><div className="page-meta">{kind}</div></div>{res.meta.stale&&<StaleNotice asOf={res.meta.asOf}/>}<div className="metrics" style={{marginTop:res.meta.stale?12:0}}><Metric label="Markets" value={s.marketCount.toLocaleString()}/>{kind!=="asset"&&<Metric label="Assets" value={s.assetCount.toLocaleString()}/>} {kind!=="protocol"&&<Metric label="Protocols" value={s.protocolCount.toLocaleString()}/>} {kind!=="chain"&&<Metric label="Chains" value={s.chainCount.toLocaleString()}/>}<Metric label="Tracked deposits / TVL" value={usd(s.depositsUsd)}/><Metric label="Liquidity" value={usd(s.liquidityUsd)}/><Metric label="Median yield" value={pct(s.medianRate)}/><Metric label="Best yield" value={pct(s.bestRate)}/>{(kind==="protocol"||kind==="chain")&&<Metric label="Debt" value={usd(s.debtUsd)}/>} {(kind==="protocol"||kind==="chain")&&<Metric label="Utilization" value={pct(s.utilization,1)}/>}</div>
<section className="panel section"><div className="panel-head"><span className="panel-title">Yield History</span></div><div className="panel-body">{d.history.length?<TimeChart series={[{name:"Median yield",data:d.history.map(x=>[x.observedAt,x.rate])},{name:"Borrow",data:d.history.map(x=>[x.observedAt,x.borrowRate])}]}/>:<Unavailable title="History is accumulating"/>}</div></section>
<section className="section analytics-grid two"><Panel title="Fixed vs Floating">{d.history.length?<TimeChart series={[{name:"Fixed",data:d.history.map(x=>[x.observedAt,x.fixedRate])},{name:"Floating",data:d.history.map(x=>[x.observedAt,x.floatingRate])}]}/>:<Unavailable title="Insufficient history"/>}</Panel><Panel title="Liquidity and TVL">{d.history.length?<TimeChart yFormat="usd" series={[{name:"TVL / deposits",data:d.history.map(x=>[x.observedAt,x.tvlUsd])},{name:"Liquidity",data:d.history.map(x=>[x.observedAt,x.liquidityUsd])}]}/>:<Unavailable title="Insufficient history"/>}</Panel></section>
<section className="section analytics-grid two"><Panel title={kind==="protocol"?"Asset Composition":"Protocol Breakdown"}>{breakdown.length?<TreemapChart rows={breakdown.map(x=>({label:x.label,value:x.value??0,detail:`${x.markets} markets`}))}/>:<Unavailable title="Breakdown unavailable"/>}</Panel><Panel title="Chain Breakdown">{secondary.length?<HorizontalBarChart rows={secondary.map(x=>({label:x.label,value:x.value??0}))}/>:<Unavailable title="Breakdown unavailable"/>}</Panel></section>
<section className="section analytics-grid two"><Panel title="Yield Distribution">{d.distribution.length?<DistributionChart values={d.distribution} current={s.medianRate}/>:<Unavailable title="Insufficient history"/>}</Panel><Panel title="Yield Curve">{curve.length?<CurveChart points={curve}/>:<Unavailable title="No maturity curve available"/>}</Panel></section>
<section className="section analytics-grid two"><Panel title="Yield Landscape" note="Tenor × yield · bubble = liquidity">{bubbles.length?<BubbleChart points={bubbles}/>:<Unavailable title="No maturity landscape available"/>}</Panel><Panel title="Market Relationship Map"><RelationshipGraph entityLabel={label} markets={d.landscape}/></Panel></section>
<section className="panel section"><div className="panel-head"><span className="panel-title">Yield Flow</span><span className="panel-note">Observed market structure</span></div><div className="panel-body"><FlowDiagram mode="yield"/></div></section>
<section className="section"><h2 className="section-title">Markets</h2><MarketsTable rows={d.markets} selectable/></section></div>}
function Panel({title,note,children}:{title:string;note?:string;children:React.ReactNode}){return <div className="panel"><div className="panel-head"><span className="panel-title">{title}</span>{note&&<span className="panel-note">{note}</span>}</div><div className="panel-body">{children}</div></div>}
