"use client";
import * as echarts from "echarts";
import {useEffect,useRef} from "react";

const css=(name:string)=>getComputedStyle(document.documentElement).getPropertyValue(name).trim();
function useEchart(build:()=>echarts.EChartsOption,deps:unknown[]){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current,null,{renderer:"canvas"});const render=()=>chart.setOption(build(),true);render();const ro=new ResizeObserver(()=>chart.resize());ro.observe(ref.current);const mo=new MutationObserver(render);mo.observe(document.documentElement,{attributes:true,attributeFilter:["data-theme"]});return()=>{ro.disconnect();mo.disconnect();chart.dispose()};// eslint-disable-next-line react-hooks/exhaustive-deps
},deps);return ref}
function Frame({children,label}:{children:React.ReactNode;label:string}){const shell=useRef<HTMLDivElement>(null);return <div className="chart-shell" ref={shell}><div className="chart-toolbar"><button type="button" className="chart-action" onClick={()=>shell.current?.requestFullscreen?.()}>Full screen</button></div><div aria-label={label}>{children}</div></div>}

export function TreemapChart({rows,height=300}:{rows:Array<{label:string;value:number;detail?:string}>;height?:number}){const ref=useEchart(()=>({tooltip:{formatter:(p:unknown)=>{const d=(p as{data:{name:string;value:number;detail?:string}}).data;return `${d.name}<br/>$${Number(d.value).toLocaleString(undefined,{maximumFractionDigits:0})}${d.detail?`<br/>${d.detail}`:""}`}},series:[{type:"treemap",roam:false,nodeClick:false,breadcrumb:{show:false},label:{show:true,color:css("--text"),fontSize:10,formatter:"{b}"},upperLabel:{show:false},itemStyle:{borderColor:css("--surface"),borderWidth:2,gapWidth:2},levels:[{itemStyle:{borderColor:css("--surface"),borderWidth:2,gapWidth:2}}],data:rows.filter(x=>x.value>0).map((x,i)=>({name:x.label,value:x.value,detail:x.detail,itemStyle:{color:i%2?css("--green-2"):css("--green")}}))}]}),[rows]);return <Frame label="Treemap"><div ref={ref} className="chart" style={{height}}/></Frame>}

type Pair={xKey:string;yKey:string;coefficient:number|null;samples:number;sampleFrom:string|null;sampleTo:string|null};
export function CorrelationMatrix({labels,pairs,height=420}:{labels:Array<{key:string;label:string}>;pairs:Pair[];height?:number}){const index=new Map(labels.map((x,i)=>[x.key,i]));const cells=pairs.flatMap(p=>{const x=index.get(p.xKey),y=index.get(p.yKey);if(x==null||y==null||p.coefficient==null)return[];const base:[[number,number,number,number,string|null,string|null]]=[[x,y,p.coefficient,p.samples,p.sampleFrom,p.sampleTo]];return x===y?base:[...base,[y,x,p.coefficient,p.samples,p.sampleFrom,p.sampleTo] as [number,number,number,number,string|null,string|null]]});const ref=useEchart(()=>({grid:{left:120,right:24,top:18,bottom:110},tooltip:{formatter:(raw:unknown)=>{const d=(raw as{data:[number,number,number,number,string|null,string|null]}).data;return `${labels[d[1]]?.label??""} × ${labels[d[0]]?.label??""}<br/>Correlation ${d[2].toFixed(3)}<br/>${d[3]} overlapping observations${d[4]&&d[5]?`<br/>${String(d[4]).slice(0,10)} → ${String(d[5]).slice(0,10)}`:""}`}},xAxis:{type:"category",data:labels.map(x=>x.label),axisLabel:{rotate:42,color:css("--muted"),fontSize:9},axisLine:{lineStyle:{color:css("--border")}}},yAxis:{type:"category",data:labels.map(x=>x.label),axisLabel:{color:css("--muted"),fontSize:9},axisLine:{lineStyle:{color:css("--border")}}},visualMap:{min:-1,max:1,calculable:false,orient:"horizontal",left:"center",bottom:18,text:["+1","-1"],textStyle:{color:css("--muted"),fontSize:9},inRange:{color:[css("--danger"),css("--surface-2"),css("--green")]}},series:[{type:"heatmap",data:cells,label:{show:false},emphasis:{itemStyle:{borderColor:css("--text"),borderWidth:1}}}]}),[labels,pairs]);return <Frame label="Correlation matrix"><div ref={ref} className="chart" style={{height}}/></Frame>}

export function RelationshipGraph({entityLabel,markets,height=350}:{entityLabel:string;markets:Array<{id:string;market_name:string;protocol_id:string;protocol_name:string|null;chain_id:string;chain_name:string|null;asset_id:string;asset_symbol:string|null;maturity:string|null}>;height?:number}){const root="root",nodes=new Map<string,{id:string;name:string;category:number;symbolSize:number}>();nodes.set(root,{id:root,name:entityLabel,category:0,symbolSize:42});const links:Array<{source:string;target:string}>=[];for(const m of markets.slice(0,45)){const p=`p:${m.protocol_id}`,c=`c:${m.chain_id}`,a=`a:${m.asset_id}`,mk=`m:${m.id}`;if(!nodes.has(p))nodes.set(p,{id:p,name:m.protocol_name??m.protocol_id,category:1,symbolSize:24});if(!nodes.has(c))nodes.set(c,{id:c,name:m.chain_name??m.chain_id,category:2,symbolSize:22});if(!nodes.has(a))nodes.set(a,{id:a,name:m.asset_symbol??m.asset_id,category:3,symbolSize:22});if(!nodes.has(mk))nodes.set(mk,{id:mk,name:m.market_name,category:4,symbolSize:12});links.push({source:root,target:mk},{source:mk,target:p},{source:mk,target:c},{source:mk,target:a})}const ref=useEchart(()=>({tooltip:{formatter:(p:unknown)=>(p as{name?:string}).name??""},legend:[{data:["Entity","Protocol","Chain","Asset","Market"],textStyle:{color:css("--muted"),fontSize:9}}],series:[{type:"graph",layout:"force",roam:true,draggable:true,categories:[{name:"Entity"},{name:"Protocol"},{name:"Chain"},{name:"Asset"},{name:"Market"}],data:[...nodes.values()].map((n,i)=>({...n,itemStyle:{color:[css("--green"),css("--info"),css("--warning"),css("--green-2"),css("--muted")][n.category]},label:{show:i===0||n.category<4,color:css("--text"),fontSize:9}})),links,lineStyle:{color:css("--border-strong"),opacity:.65,width:1},force:{repulsion:110,edgeLength:[40,100],gravity:.08},emphasis:{focus:"adjacency"}}]}),[entityLabel,markets]);return <Frame label="Market relationship map"><div ref={ref} className="chart" style={{height}}/></Frame>}

export function ScatterCompareChart({points,xLabel,yLabel,bubbleLabel,height=340}:{points:Array<{label:string;x:number;y:number;bubble:number}>;xLabel:string;yLabel:string;bubbleLabel:string;height?:number}){const max=Math.max(1,...points.map(x=>Math.abs(x.bubble)));const ref=useEchart(()=>({grid:{left:70,right:24,top:18,bottom:54},tooltip:{formatter:(raw:unknown)=>{const d=(raw as{data:[number,number,number,string]}).data;return `${d[3]}<br/>${xLabel}: ${d[0].toLocaleString()}<br/>${yLabel}: ${d[1].toLocaleString()}<br/>${bubbleLabel}: ${d[2].toLocaleString()}`}},xAxis:{type:"value",name:xLabel,nameLocation:"middle",nameGap:36,nameTextStyle:{color:css("--muted")},axisLabel:{color:css("--muted"),fontSize:9},splitLine:{lineStyle:{color:css("--border")}}},yAxis:{type:"value",name:yLabel,nameTextStyle:{color:css("--muted")},axisLabel:{color:css("--muted"),fontSize:9},splitLine:{lineStyle:{color:css("--border")}}},dataZoom:[{type:"inside"}],series:[{type:"scatter",data:points.map(p=>[p.x,p.y,p.bubble,p.label]),symbolSize:(raw:unknown)=>{const d=raw as number[];return Math.max(8,Math.min(34,8+26*Math.sqrt(Math.abs(d[2]??0)/max)))},itemStyle:{color:css("--green"),opacity:.72},emphasis:{focus:"self",itemStyle:{opacity:1}}}]}),[points,xLabel,yLabel,bubbleLabel]);return <Frame label="Comparison scatter"><div ref={ref} className="chart" style={{height}}/></Frame>}

export function FlowDiagram({mode}:{mode:"yield"|"fixed"|"floating"|"basis"|"execution"}){const steps=mode==="yield"?["Asset","Protocol","Market","Yield"]:mode==="fixed"?["Underlying Yield","PT Pricing","Maturity","Effective Fixed Return"]:mode==="floating"?["Borrow Demand","Utilization","Rate Model","Supply APR","Rewards","Effective Yield"]:mode==="basis"?["Fixed Yield","Comparison Engine","Floating Yield","Basis"]:["Headline Yield","Position Size","Depth","Price Impact","Effective Yield"];return <div className="flow-diagram" aria-label={`${mode} analytical flow`}>{steps.map((step,i)=><div className="flow-step" key={step}><span>{step}</span>{i<steps.length-1&&<b aria-hidden="true">→</b>}</div>)}</div>}
