import{createHash}from"node:crypto";import type{Asset,Chain,Market,MarketSnapshot,Protocol}from"@tokos-data/contracts";import type{OneDeltaLatestItem,OneDeltaLatestMarket}from"./onedelta.js";import type{PendleMarket,PendleHistoricalPoint}from"./pendle.js";
export const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export const payloadHash=(p:unknown)=>createHash("sha256").update(JSON.stringify(p)).digest("hex");
export const pctToDecimal=(v:number|null|undefined)=>v===null||v===undefined||!Number.isFinite(v)?null:v/100;
export function classifyAsset(symbol:string):Asset["category"]{const s=symbol.toUpperCase();if(/^(USDC|USDT|DAI|FRAX|USDE|SUSDE|USDS|GHO|LUSD|USD0|PYUSD|RLUSD|FDUSD)/.test(s))return"stablecoin";if(/^(ETH|WETH)$/.test(s))return"eth";if(/^(BTC|WBTC|TBTC|CBBTC)$/.test(s))return"btc";if(/^(STETH|WSTETH|RETH|CBETH|SFRXETH)$/.test(s))return"lst";if(/^(EETH|WEETH|EZETH|RSETH|PUFETH)$/.test(s))return"lrt";return"other";}
export function canonicalAssetGroup(symbol:string){const s=symbol.toUpperCase();if(["USDC","USDBC"].includes(s))return"usdc";if(["USDT","USD₮0"].includes(s))return"usdt";if(["ETH","WETH"].includes(s))return"eth";if(["BTC","WBTC","CBBTC","TBTC"].includes(s))return"btc";if(["USDE","SUSDE"].includes(s))return"usde";return slugify(s);}
function odAsset(m:OneDeltaLatestMarket):Asset{const x=m.underlyingInfo?.asset??m.underlying??{},symbol=x.symbol??"UNKNOWN",address=x.address?.toLowerCase(),id=address?`${slugify(symbol)}:${address}`:slugify(symbol);return{id,symbol,name:x.name??symbol,assetGroup:canonicalAssetGroup(symbol),decimals:x.decimals??m.decimals??null,logoUrl:x.logoURI??null,category:classifyAsset(symbol),stablecoinPeg:classifyAsset(symbol)==="stablecoin"?"USD":null};}
export function normalizeOneDeltaMarket(item:OneDeltaLatestItem,source:OneDeltaLatestMarket,chainName:string){const asset=odAsset(source),key=source.lenderKey??item.lenderInfo.key,providerMarketId=source.marketUid??`${key}:${item.chainId}:${source.poolId??asset.id}`,protocolId=`1delta:${slugify(key)}`,fixed=Boolean(item.fixedTerm)||(source.terms?.length??0)>0,observedAt=new Date(item.lastFetched).toISOString();
 const protocol:Protocol={id:protocolId,slug:slugify(item.lenderInfo.name||key),name:item.lenderInfo.name||key,logoUrl:item.lenderInfo.logoURI??null,providerKeys:[key],categories:["lending"],websiteUrl:null};
 const chain:Chain={id:item.chainId,slug:slugify(chainName||`chain-${item.chainId}`),name:chainName||`Chain ${item.chainId}`,logoUrl:null,nativeAssetSymbol:null,active:true};
 const id=`1delta:${providerMarketId}`;const market:Market={id,provider:"1delta",providerMarketId,protocolId,chainId:item.chainId,assetId:asset.id,quoteAssetId:null,marketType:fixed?"fixed-term":"lending",rateType:fixed?"hybrid":"floating",maturity:item.fixedTerm?.maturity?new Date(item.fixedTerm.maturity*1000).toISOString():null,marketAddress:source.poolId??null,marketName:`${protocol.name} ${asset.symbol}`,status:"active",executionModel:"provider-simulated"};
 const supply=pctToDecimal(source.depositRate);const snapshot:MarketSnapshot={marketId:id,observedAt,sourceObservedAt:observedAt,ingestedAt:new Date().toISOString(),supplyApr:supply,borrowApr:pctToDecimal(source.variableBorrowRate),fixedApy:null,impliedApy:null,underlyingApy:null,depositsUsd:source.totalDepositsUsd??null,debtUsd:source.totalDebtUsd??null,liquidityUsd:source.totalLiquidityUsd??null,tvlUsd:source.totalDepositsUsd!=null?source.totalDepositsUsd-(source.totalDebtUsd??0):null,utilization:source.utilization??null,volume24hUsd:null,rewardApr:null,intrinsicApr:pctToDecimal(source.intrinsicYield),aprExRewards:supply,stale:false,rawPayloadHash:payloadHash(source)};
 return{asset,chain,protocol,market,snapshot,raw:source};
}
export function normalizePendleMarket(source:PendleMarket){const u=source.underlyingAsset??source.sy??source.pt??{},symbol=u.symbol??source.pt?.symbol?.replace(/^PT-/,"")??"UNKNOWN",address=u.address?.toLowerCase(),assetId=address?`${slugify(symbol)}:${address}`:slugify(symbol);const asset:Asset={id:assetId,symbol,name:u.name??symbol,assetGroup:canonicalAssetGroup(symbol),decimals:u.decimals??null,logoUrl:null,category:classifyAsset(symbol),stablecoinPeg:classifyAsset(symbol)==="stablecoin"?"USD":null};const protocol:Protocol={id:"pendle",slug:"pendle",name:"Pendle",logoUrl:null,providerKeys:["pendle"],categories:["fixed-yield","yield-trading"],websiteUrl:"https://pendle.finance"};const chain:Chain={id:source.chainId,slug:`chain-${source.chainId}`,name:`Chain ${source.chainId}`,logoUrl:null,nativeAssetSymbol:null,active:true};const id=`pendle:${source.chainId}:${source.address.toLowerCase()}`,expiryMs=typeof source.expiry==="number"?(source.expiry>1e12?source.expiry:source.expiry*1000):(/^\\d+(?:\\.\\d+)?$/.test(source.expiry)?Number(source.expiry)*(Number(source.expiry)>1e12?1:1000):Date.parse(source.expiry)),maturity=new Date(expiryMs),matured=Number.isFinite(expiryMs)&&maturity.getTime()<=Date.now();const market:Market={id,provider:"pendle",providerMarketId:`${source.chainId}:${source.address.toLowerCase()}`,protocolId:"pendle",chainId:source.chainId,assetId,quoteAssetId:null,marketType:"pt",rateType:"fixed",maturity:maturity.toISOString(),marketAddress:source.address.toLowerCase(),marketName:source.name??`${source.pt?.symbol??"PT"} ${symbol}`,status:matured?"matured":"active",executionModel:"provider-exact"};const observedAt=new Date().toISOString();const snapshot:MarketSnapshot={marketId:id,observedAt,sourceObservedAt:null,ingestedAt:observedAt,supplyApr:null,borrowApr:null,fixedApy:source.impliedApy??null,impliedApy:source.impliedApy??null,underlyingApy:source.underlyingApy??null,depositsUsd:null,debtUsd:null,liquidityUsd:source.liquidity?.usd??null,tvlUsd:source.tvl?.usd??null,utilization:null,volume24hUsd:source.volume24h?.usd??null,rewardApr:null,intrinsicApr:null,aprExRewards:null,stale:false,rawPayloadHash:payloadHash(source)};return{asset,chain,protocol,market,snapshot};}
export function normalizePendleHistoryPoint(marketId:string,p:PendleHistoricalPoint,rawHash:string):MarketSnapshot{const t=typeof p.timestamp==="number"?new Date(p.timestamp>1e10?p.timestamp:p.timestamp*1000):new Date(p.timestamp);return{marketId,observedAt:t.toISOString(),sourceObservedAt:t.toISOString(),ingestedAt:new Date().toISOString(),supplyApr:null,borrowApr:null,fixedApy:p.impliedApy??null,impliedApy:p.impliedApy??null,underlyingApy:p.underlyingApy??null,depositsUsd:null,debtUsd:null,liquidityUsd:p.liquidity??null,tvlUsd:p.tvl??null,utilization:null,volume24hUsd:p.volume??null,rewardApr:null,intrinsicApr:null,aprExRewards:null,stale:false,rawPayloadHash:rawHash};}
