import{z}from"zod";import{fetchJson}from"./http.js";
const token=z.object({address:z.string().optional(),symbol:z.string().optional(),name:z.string().optional(),decimals:z.number().optional(),price:z.object({usd:z.number().nullable().optional()}).passthrough().optional()}).passthrough();
const market=z.object({chainId:z.coerce.string(),address:z.string(),expiry:z.number(),impliedApy:z.number().nullable().optional(),underlyingApy:z.number().nullable().optional(),tvl:z.object({usd:z.number().nullable().optional()}).passthrough().optional(),liquidity:z.object({usd:z.number().nullable().optional()}).passthrough().optional(),volume24h:z.object({usd:z.number().nullable().optional()}).passthrough().optional(),pt:token.optional(),yt:token.optional(),sy:token.optional(),underlyingAsset:token.optional(),name:z.string().optional()}).passthrough();
const list=z.object({markets:z.array(market),total:z.number().optional()}).passthrough();
const hist=z.object({timestamp:z.union([z.string(),z.number()]),impliedApy:z.number().nullable().optional(),underlyingApy:z.number().nullable().optional(),tvl:z.number().nullable().optional(),volume:z.number().nullable().optional(),liquidity:z.number().nullable().optional()}).passthrough();
const marketTokensSchema=z.object({tokensMintSy:z.array(z.string()).default([]),tokensRedeemSy:z.array(z.string()).default([]),tokensIn:z.array(z.string()).default([]),tokensOut:z.array(z.string()).default([])}).passthrough();
const convertRouteSchema=z.object({outputs:z.array(z.object({token:z.string(),amount:z.string()}).passthrough()).optional(),data:z.object({priceImpact:z.number().nullable().optional(),impliedApy:z.object({before:z.number(),after:z.number()}).passthrough().nullable().optional(),effectiveApy:z.number().nullable().optional(),fee:z.object({usd:z.number().nullable().optional()}).passthrough().nullable().optional()}).passthrough().optional()}).passthrough();
const convertSchema=z.object({action:z.string().optional(),routes:z.array(convertRouteSchema).default([])}).passthrough();
export type PendleMarket=z.infer<typeof market>;export type PendleHistoricalPoint=z.infer<typeof hist>;
export class PendleClient{
 constructor(private readonly options:{baseUrl:string;apiKey?:string|undefined}){}
 private headers():HeadersInit{return this.options.apiKey?{authorization:`Bearer ${this.options.apiKey}`}:{}}
 async allMarkets(){const markets:PendleMarket[]=[],rawPages:unknown[]=[];const limit=100;for(let skip=0;;skip+=limit){const url=`${this.options.baseUrl}/v2/markets/all?limit=${limit}&skip=${skip}`;const{data}=await fetchJson<unknown>("pendle",url,{headers:this.headers()});const p=list.parse(data);markets.push(...p.markets);rawPages.push(data);if(p.markets.length<limit||(p.total!==undefined&&markets.length>=p.total))break;}return{markets,rawPages};}
 async historicalData(chainId:string,address:string,from?:string,to?:string){const q=new URLSearchParams();if(from)q.set("start",from);if(to)q.set("end",to);const url=`${this.options.baseUrl}/v3/${chainId}/markets/${address}/historical-data${q.size?`?${q}`:""}`;const{data,status}=await fetchJson<unknown>("pendle",url,{headers:this.headers()});const c=z.union([z.array(hist),z.object({results:z.array(hist).optional(),data:z.array(hist).optional()}).passthrough()]).parse(data);const points=Array.isArray(c)?c:c.results??c.data??[];return{points,raw:data,status,endpoint:url};}
 async marketTokens(chainId:string,address:string){const url=`${this.options.baseUrl}/v1/sdk/${chainId}/markets/${address}/tokens`;const{data,status}=await fetchJson<unknown>("pendle",url,{headers:this.headers()});return{parsed:marketTokensSchema.parse(data),raw:data,status,endpoint:url};}
 async convertV3(chainId:string,body:unknown){const url=`${this.options.baseUrl}/v3/sdk/${chainId}/convert`;const{data,status}=await fetchJson<unknown>("pendle",url,{method:"POST",headers:{"content-type":"application/json",...this.headers()},body:JSON.stringify(body)});return{parsed:convertSchema.parse(data),raw:data,status,endpoint:url};}
}
